import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MulAI - Multi genAI",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <header className="flex h-fit bg-blue-500 text-white text-xl p-4 md:h-fit mb-6">
          <h1 className="font-bold"><a href="/">MulAI</a></h1>
          {/* <span><a onClick={clearConversation}>×</a></span> */}
        </header>
        {children}
      </body>
    </html>
  );
}
